"""add bio and profile pic path

Revision ID: 596001d1cb39
Revises: df6c7e54e4d7
Create Date: 2020-06-09 18:02:42.520948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '596001d1cb39'
down_revision = 'df6c7e54e4d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_pic_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic_path')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
